API_BASE_URL = "https://api.mercadolibre.com"
SEARCH_URL = f"{API_BASE_URL}/sites/MLU/search"
ITEM_URL = f"{API_BASE_URL}/items/"

MIN_PRICE = 13000
MAX_PRICE = 19000
DEFAULT_CATEGORY = "MLU1459"
DEFAULT_STATE = "TUxVUE1PTjQxN2E4"  # Montevideo
DEFAULT_PRICE_RANGE = f"{MIN_PRICE}UYU-{MAX_PRICE}UYU"
DEFAULT_CURRENCY = "UYU"
DEFAULT_PROPERTY_TYPE = "242062,242060"  # Apartamento, Casa
DEFAULT_AREA = "[0-*)" 

WANTED_CITIES = [
    "TUxVQ0xBWjk5YTE5",
    "TUxVQ0NFTjVjMTM",
    "TUxVQ0NPUjZmZjNm",
    "TUxVQ1BPQzM5ZGRi",
    "TUxVQ01BTDE0YmY1",
    "TUxVQ0JVQzNlMDdl",
    "TUxVQ0NBUmRhYWU0",
    "TUxVQ1BBUjVkNGE4",
    "TUxVQ1BBUmU3Y2Nj",
    "TUxVQ1BPQzIwNDU",
    "TUxVQ1BVRTI0NDA",
    "TUxVQ1BVTjJmMjkx",
    "TUxVQ1BVTjYxODI",
    "TUxVQ1RSRTg3OGM3",
    "TUxVQ1ZJTDE2MDU",
    "TUxVQ1ZJTDk1MTY"
]

BLOCKED_SELLERS = []

DEFAULT_LIMIT = 50
DEFAULT_OFFSET = 0 

REQUEST_DELAY = 2

SEARCH_SINCE = "today"

LOG_LEVEL = "INFO"
